Hw 11 pecs
mate-academy/jv-pecs pull request #115
Opened 2021-04-12 08:37 UTC by IhorRome

2021-04-13 08:16 UTC, vuyko23 approved these changes

2021-04-13 08:16 UTC, vuyko23 commented on src/main/java/core/mate/academy/model/Bulldozer.java
> +        return List.of(oneCubeBulldozer, oneAndHalfCubeBulldozer);
If you want you can use parents fild name,color in your constructor

2021-04-13 13:31 UTC, KseniiaMakarova requested changes

2021-04-13 13:31 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/model/Machine.java
> +public abstract class Machine implements Workable, MachineProducer {
```suggestion
public abstract class Machine implements Workable {
```
you should create 3 Producer classes (1 for each type of machine) and override `get()` method there

2021-04-13 13:31 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineProducer.java
> +    List<Machine> get();
let's make this method return List of any Machine (`List<Excavator>` or `List<Truck>`)

2021-04-13 13:31 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineService.java
> +    List<Machine> getAll(Class<? extends Machine> type);
in all method signatures of this class - let's not bind to the machines
you can operate `T` instead

2021-04-13 13:31 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +public class MachineServiceImpl<T extends Machine> implements MachineService<T> {
```suggestion
public class MachineServiceImpl implements MachineService<Machine> {
```

2021-04-13 13:31 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +                : type.equals(Bulldozer.class) ? bulldozer.get()
```suggestion
        return type.equals(Truck.class) ? new ArrayList(truckProducer.get())
                : type.equals(Bulldozer.class) ? new ArrayList(bulldozerProducer.get())
                ...
```

2021-04-14 07:15 UTC, KseniiaMakarova requested changes
good job!

2021-04-14 07:15 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/model/Truck.java
> +    private int wheelAmount;
```suggestion
    private int numberOfWheels;
```

2021-04-14 07:15 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineService.java
> +    List<T> getAll(Class<? extends Machine> type);
let's use `T` everywhere

2021-04-14 09:06 UTC, KseniiaMakarova approved these changes

2024-10-14 09:12 UTC, closed without merging