jv-pecs
mate-academy/jv-pecs pull request #200
Opened 2021-12-17 15:02 UTC by morozovyrv

2021-12-17 15:26 UTC, RomanDubovskyi requested changes

2021-12-17 15:26 UTC, RomanDubovskyi commented on src/main/java/core/mate/academy/service/MachineService.java
> +    <E> List<E> getAll(Class type);
```suggestion
     List<E> getAll(Class type);
```
так як це не статичний метод, його можна окремо не парамтеризовувати

2021-12-17 15:26 UTC, RomanDubovskyi commented on src/main/java/core/mate/academy/service/MachineService.java
> +    <E> List<E> getAll(Class type);
давай параметризуємо Class

2021-12-17 15:26 UTC, RomanDubovskyi commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +    public List<?> getAll(Class type) {
чому List<?>

2021-12-20 10:47 UTC, MaliukDaria approved these changes

2023-02-02 13:51 UTC, closed without merging