Solution of my implementation  MachineServise Int
mate-academy/jv-pecs pull request #223
Opened 2022-01-31 21:05 UTC by dima-semeniuk

2022-02-01 11:09 UTC, yurii-tomashevskyi commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +        for (int i = 0; i < machines.size(); i++) {
I think beter use for each loop

2022-02-02 09:18 UTC, AlexRozv requested changes

2022-02-02 09:18 UTC, AlexRozv commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +            return machines;
why do you have to fill your list of machines and then return it if you can just return new BulldozerProducer().get()

2022-02-02 09:18 UTC, AlexRozv commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +    }
also, you can remove machines list completely and just return empty list here

2022-02-02 11:07 UTC, AlexRozv approved these changes
well done ✅

2023-10-02 10:52 UTC, closed without merging