Model classes appended. Producers and Service implemented
mate-academy/jv-pecs pull request #341
Opened 2022-08-22 10:00 UTC by SpaceUrgent

2022-08-22 13:48 UTC, aaananas requested changes

2022-08-22 13:48 UTC, aaananas commented on src/main/java/core/mate/academy/model/Truck.java
>   */
remove all comments
```suggestion
```

2022-08-22 13:48 UTC, aaananas commented on src/main/java/core/mate/academy/service/MachineProducer.java
>  public interface MachineProducer {
```suggestion
public interface MachineProducer<T extends Machine> {
```

2022-08-22 13:48 UTC, aaananas commented on src/main/java/core/mate/academy/service/MachineProducer.java
> +    List<? extends Machine> get();
```suggestion
    List<T> get();
```

2022-08-22 13:48 UTC, aaananas commented on src/main/java/core/mate/academy/service/MachineService.java
> +    void startWorking(List<? extends Machine> machines);
```suggestion
    void startWorking(List<? extends T> machines);
```

2022-08-22 13:48 UTC, aaananas commented on src/main/java/core/mate/academy/service/MachineService.java
> +    void fill(List<? super Machine> machines, T value);
```suggestion
    void fill(List<? super T> machines, T value);
```

2022-08-22 13:48 UTC, aaananas commented on src/main/java/core/mate/academy/service/MachineService.java
> +    List<T> getAll(Class<? extends Machine> type);
```suggestion
    List<T> getAll(Class<? extends T> type);
```

2022-08-22 18:00 UTC, zachar-chorny requested changes

2022-08-22 18:00 UTC, zachar-chorny commented on src/main/java/core/mate/academy/service/impl/MachineServiceImpl.java
> +            machines.add(i, value);
use machines.set() instead of remove and add

2022-08-23 11:52 UTC, MaliukDaria requested changes

2022-08-23 11:52 UTC, MaliukDaria commented on src/main/java/core/mate/academy/service/impl/BulldozerProducer.java
> +public class BulldozerProducer implements MachineProducer {
```suggestion
public class BulldozerProducer implements MachineProducer< Bulldozer > {
```

same for other classes

2022-08-24 07:21 UTC, zachar-chorny approved these changes

2025-03-09 18:11 UTC, closed without merging