MachineService implemented
mate-academy/jv-pecs pull request #376
Opened 2022-10-09 15:25 UTC by Pavlo-Gook

2022-10-11 09:33 UTC, alex-anofriev commented on src/main/java/core/mate/academy/service/MachineProducer.java
> +    List<? extends Machine> get();
I think you can use here just T because in interface you already wrote that T extends Machine

2022-10-11 09:33 UTC, alex-anofriev commented on src/main/java/core/mate/academy/service/MachineService.java
> +    void fill(List<? super Machine> machines, Machine value);
Here also I guess Machine can be replaced with T as in interface you wrote that T extends Machine

2022-10-11 10:37 UTC, alex-anofriev approved these changes

2022-10-17 10:26 UTC, ChumakAn approved these changes

2022-10-18 07:40 UTC, ChumakAn requested changes
Well done, if you want to make it better, than ->
<img width="433" alt="image" src="https://user-images.githubusercontent.com/72727656/196366934-bca1d61c-aedb-4151-91cf-293986077357.png">
it's better to add some logic to the hierarchy of classes, also you can use super() in child classes to inherit the fields and make this class structure better-looking
Also, what's the reason to use the LinkedList?

2022-10-18 07:40 UTC, ChumakAn commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +            return new LinkedList<>(new BulldozerProducer().get());
why do you use the LinkedList?

2022-10-18 07:42 UTC, ChumakAn approved these changes

2024-12-15 15:05 UTC, closed without merging