created implementations of MachineProducer and Machineservice interfaces
mate-academy/jv-pecs pull request #518
Opened 2023-02-19 11:35 UTC by outref

2023-02-19 19:18 UTC, NazarZva approved these changes
good job

2023-02-22 11:12 UTC, KseniiaMakarova requested changes

2023-02-22 11:12 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineProducer.java
>  public interface MachineProducer {
Please parameterize your MachineProducer
```suggestion
public interface MachineProducer<...> {
```

2023-02-22 11:12 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/ExcavatorProducer.java
> +public class ExcavatorProducer implements MachineProducer {
```suggestion
public class ExcavatorProducer implements MachineProducer<Excavator> {
```

2023-02-22 11:12 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/ExcavatorProducer.java
> +    public List<Machine> get() {
```suggestion
    public List<Excavator> get() {
```

2023-02-22 11:12 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/ExcavatorProducer.java
> +            excavatorList.add(new Excavator());
we can add some exclusive fields to each child machine to make them more unique

2023-02-22 11:12 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineService.java
> +public interface MachineService<T extends Workable> {
```suggestion
public interface MachineService<T extends Machine> {
```

2023-02-22 11:12 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineService.java
> +    List<Machine> getAll(Class<? extends Machine> type);
```suggestion
    List<T> getAll(Class<? extends T> type);
```

2023-02-22 11:12 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineService.java
> +    void fill(List<? super Machine> machines, Machine value);
```suggestion
    void fill(List<? super T> machines, T value);
```

2023-02-22 11:12 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineService.java
> +    void startWorking(List<? extends Workable> machines);
```suggestion
    void startWorking(List<? extends T> machines);
```

2023-02-22 11:12 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +
```suggestion
```

2023-02-22 11:12 UTC, KseniiaMakarova commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +                return new ExcavatorProducer().get();
https://mate-academy.github.io/jv-program-common-mistakes/java-core/pecs/pecs.html#consider-creating-a-local-variable-in-your-implementation-of-getallclass-type-method

2023-02-24 12:27 UTC, Andriy-dz approved these changes

2025-08-25 04:05 UTC, closed without merging