implement MachineProducer and MachineService with PECS
mate-academy/jv-pecs pull request #551
Opened 2023-03-22 20:22 UTC by fed4ik

2023-03-23 10:43 UTC, Rommelua requested changes
Task is not done 
![image](https://user-images.githubusercontent.com/20326858/227178920-7aea2c7b-a894-45df-aa8e-cd53f5e36986.png)

Also, before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected.
https://mate-academy.github.io/jv-program-common-mistakes/java-core/pecs/pecs.html

2023-03-24 15:43 UTC, andriy-shulepa requested changes

2023-03-24 15:43 UTC, andriy-shulepa commented on src/test/java/core/mate/academy/service/MachineServiceTest.java
> -
needless change. static imports should be separated with empty line from non-static imports

2023-03-24 15:43 UTC, andriy-shulepa commented on src/main/java/core/mate/academy/service/BulldozerProducer.java
> +    public List<? extends Machine> get() {
```suggestion
    public List<Buldozer> get() {
```
concrete produces produces concrete machines. fox in all places

2023-03-24 15:43 UTC, andriy-shulepa commented on src/main/java/core/mate/academy/service/MachineProducer.java
> +    List<? extends Machine> get();
```suggestion
    List<T> get();
```

parameterized producer should produce object of its parameter

2023-03-24 15:43 UTC, andriy-shulepa commented on src/main/java/core/mate/academy/service/MachineService.java
> +    List<Machine> getAll(Class type);
use parameterized type instead of Machine here and in other methods

2023-03-24 15:43 UTC, andriy-shulepa commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +            machines = new ExcavatorProducer().get();
don't create producers each time. make them class-level variables

2023-03-25 10:38 UTC, andriy-shulepa requested changes
next time create new branch and push your changes there instead of pushing to master branch

2023-03-25 10:38 UTC, andriy-shulepa commented on src/main/java/core/mate/academy/service/MachineService.java
> +    void fill(List<? super Machine> machines, Machine value);
```suggestion
    void fill(List<? super T> machines, T value);
```
fix same for startWorking method

2023-03-27 11:38 UTC, Rommelua requested changes
You should fix (or answer to) all mentor's comments before re-request new review. Be attentive and do not hesitate to contact us in Slack if you do not understand something.

2023-03-27 11:38 UTC, Rommelua commented on src/main/java/core/mate/academy/service/MachineService.java
> +    void fill(List<? super Machine> machines, Machine value);
Not fixed

2023-03-27 18:28 UTC, aaananas approved these changes

2023-03-27 18:28 UTC, aaananas commented on src/main/java/core/mate/academy/service/MachineServiceImpl.java
> +    private BulldozerProducer bulldozerProducer = new BulldozerProducer();
```suggestion
    private MachineProducer<Bulldozer> bulldozerProducer = new BulldozerProducer();
```
abstract type

2026-05-14 09:36 UTC, closed without merging